services:
  homeassistant:
    container_name: hass
    image: homeassistant/home-assistant:2021.12
    volumes:
#      - /media/data/homeassistant/homeassistant/config:/config
      - /srv/homeassistant/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    depends_on:
      - mosquitto
    environment:
      TZ: ${TZ}

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    networks:
      - network
    volumes:
#      - "/media/data/homeassistant/mosquitto/config/:/mosquitto/config"
#      - "/media/data/homeassistant/mosquitto/data:/mosquitto/data"
#      - "/media/data/homeassistant/mosquitto/log:/mosquitto/log"
      - "/srv/homeassistant/mosquitto/config/:/mosquitto/config"
      - "/srv/homeassistant/mosquitto/data:/mosquitto/data"
    ports:
      - ${MOSQUITTO_MQTT_PORT}:1883
      - ${MOSQUITTO_MQTTS_PORT}:8883
    environment:
      TZ: ${TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nodered:
    image: nodered/node-red:2.1.4
    container_name: nodered
    restart: always
    networks:
      - network
    ports:
      - "1880:1880"
    volumes:
#      - /media/data/homeassistant/nodered/data:/data
      - /srv/homeassistant/nodered/data:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "Europe/Madrid"
    user: "${PUID}"

  hass-configurator:
    image: "causticlab/hass-configurator-docker:0.4.0-arm"
    container_name: hass-configurator
    restart: always
    networks:
      - network
    ports:
      - "3218:3218/tcp"
    depends_on:
      - homeassistant
    volumes:
#      - "/media/data/homeassistant/homeassistant/configurator-config:/config"
#      - "/media/data/homeassistant/homeassistant/config:/hass-config"
      - "/srv/homeassistant/homeassistant/configurator-config:/config"
      - "/srv/homeassistant/homeassistant/config:/hass-config"
    user: "${PUID}:${PGID}"

networks:
  network:
    driver: bridge
