services:
  homeassistant:
    container_name: hass
    image: homeassistant/home-assistant
    volumes:
#      - "./run:/etc/services.d/home-assistant/run"
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    depends_on:
      - mosquitto
    environment:
        TZ: ${TZ}
        PUID: ${PGID}
        PGID: ${PGID}

  mosquitto:
    image: mosquitto
    container_name: "mosquitto"
    restart: always
    networks:
      - network
    volumes:
      - "/media/data/homeassistant/mosquitto/data:/mosquitto/data"
    ports:
      - ${MOSQUITTO_MQTT_PORT}:1883
      - ${MOSQUITTO_MQTTS_PORT}:8883
    environment:
      TZ: ${TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    networks:
      - network
    ports:
      - "1880:1880"
    volumes:
      - /media/data/homeassistant/nodered/data:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "Europe/Madrid"
    user: "${PUID}"

  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    container_name: hass-configurator
    restart: always
    networks:
      - network
    ports:
      - "3218:3218/tcp"
    depends_on:
      - homeassistant
    volumes:
      - "./configurator-config:/config"
      - "/media/data/homeassistant/homeassistant/config:/hass-config"
    user: "${PUID}:${PGID}"

networks:
  network:
    driver: bridge
