services:
  openhab:
    image: "openhab/openhab:3.2.0"
    restart: always
    hostname: 'openhab'
    container_name: 'openhab'
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/srv/openhab/userdata:/openhab/userdata"
    ports:
      - '8080:8080'
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
